import './globals.css';
import type { Metadata } from 'next';
import localFont from '@next/font/local';
import { ReactQueryProvider } from './ReactQueryProvider';

const gothicFont = localFont({
  src: [{ path: '../public/fonts/Gothic2Ingame.ttf', weight: '400' }],
  variable: '--font-gothic',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${gothicFont.variable} font-sans`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
