import './globals.css';
import 'react-loading-skeleton/dist/skeleton.css';
import type { Metadata } from 'next';
import localFont from '@next/font/local';
import { ReactQueryProvider } from './ReactQueryProvider';
import { SkeletonTheme } from 'react-loading-skeleton';

const gothicFont = localFont({
	src: [{ path: '../public/fonts/Gothic2Nacht.ttf', weight: '300' }],
	variable: '--font-gothic',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${gothicFont.variable} font-sans`}>
				<ReactQueryProvider>
					<SkeletonTheme baseColor="#0c161b" highlightColor="#3f7391">
						{children}
					</SkeletonTheme>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
